### ISSUE TITLE
importAxisValues

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#11]
Is this code necessary? With the getter/setter we can just set these values directly I believe. On the other hand, it is nice to be able to functionalize these methods for inputing/outputting data.

```
+        % function obj = importAxisValues(obj,axis_names,ax_values)
+        %     sz = size(obj);
+        %     if ischar(axis_names)
+        %         axes_indices = obj.findAxes(axis_names);
+        %     end
+        % 
+        %     for ax = 1:length(axes_indices)
+        % 
+        %         if length(ax_values) ~= sz(axes_indices(ax))
+        %             error('Mismatch between number of axis names supplied and number of axes in object.');
+        %         end
+        % 
+        %         obj.axis_pr(axes_indices(ax)).values = ax_values;
+        %     end
+        % end
```

**Comment by benpolletta** [comment]
I commented it out because I couldn't get it to work anyway...

To set axis names, I've just been assigning values directly to
obj.axis(n).name. How would I do it using the getter/setter?

**Comment by benpolletta** [comment]
9c037b7f041e1c3a48ba63c84f9328dd6830f7fb
