### ISSUE TITLE
xp.axis based on varargout

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#16]
when calling eg `xp.axis.name` or `xp.axis(1:4).name`, it only displays the first name.  Normally, structs would output all the names in the first case, or 4 names in the second case, as separate outputs, which could be concatenated with enclosing braces { }.

**Comment by erik-roberts** [comment]
This behavior is implemented in exportAxisNames and exportAxisVals. Perhaps those could be named to simply axisNames and axisValues?  I still think it would be nice to have the direct access be as expected.  You could do a check for nargout, and if its >1, use vararout same as nargout, and if nargout==1, you could give full output as expected.

**Comment by davestanley** [comment]
I tried fixing this structure enumeration issue, but could not find a solution. It seems to be a fundamental limitation of MATLAB subsref when a return value is not specified.

However, the following does work:

```
[a,b,c,d] = xp.axis.values
a =
     0
    10
    20
b =
     5
    10
    15
c =
  2×1 cell array
    'E'
    'I'
d =
  8×1 cell array
    'v'
    'iNa_m'
    'iNa_h'
    'iK_n'
    'I_iGABAa_s'
    'E_iAMPA_s'
    'I_iGABAa_ISYN'
    'E_iAMPA_ISYN'
```

**Comment by erik-roberts** [comment]
ok thanks for trying

**Comment by davestanley** [comment]
Closing this issue for now; feel free to re-open if you have other ideas
