### ISSUE TITLE
inconsistent naming convention

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#17]
this makes it hard to find functions

* i would ditch the export and get prefixes unless they are respectively saving to disk or a true getter method. thus i'd make `exportAxisVals` just `axisValues` and `getaxisinfo` to `axisSummary` or better `printSummary`/`dispSummary` since it doesn't really look good when assigned to a variable so it's more about displaying it seems.
* perhaps rename `astruct` to `info` or `meta` and implement an 'axisInfo' method.
* the nDDictAxis methods like `getvaluenoncell` are kind of hard to read as a newcomer and seem kind of wordy.

**Comment by davestanley** [comment]
Renamed getaxisinfo to printAxisInfo

**Comment by davestanley** [comment]
Renamed nDDictAxis methods like getvaluenoncell to getvalue_noncell
I'm being informal with the naming conventions of these minor supporting functions (e.g. all lowercase).

I'll probably make these methods private soon...

**Comment by erik-roberts** [comment]
ok

**Comment by davestanley** [comment]
Many nDDict methods are now protected

**Comment by davestanley** [comment]
Closing this issue now. Here's a summary of the changes I made:
1. Renamed `getaxisinfo` to `printAxisInfo`
2. Renamed `getvaluenoncell` to `getvalue_noncell` (and likewise for other getvalue methods in nDDictAxis)
3. Made many methods in `nDDictAxis` protected.
4. Renamed `nDDictAxis.astruct` to `nDDictAxis.axismeta`

**Comment by davestanley** [comment]
These changes created some issues with the following plot library files:
 
-    library_plots/xp_subplot_grid.m
-    library_plots/xp_subplot_grid3D.m
-    library_plots/xp_subplot_grid_adaptive.m
-    library_plots/xp_tight_subplot_adaptive.m

I'm going to make the getvalues_cellstr method public again and do the appropriate renaming

**Comment by davestanley** [comment]
The above issues are now fixed
