### ISSUE TITLE
get subset for numeric using values, not indices

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#18]
xp.subset('10','10') instead of xp.subset(2,2)

**Comment by benpolletta** [comment]
I think the new method axissubset (on dev_ben) should do this.

**Comment by erik-roberts** [comment]
as far as i can tell, axis subset is basically just subset but for 1 axis. so it doesn't do this.

**Comment by erik-roberts** [comment]
almost done with this

**Comment by erik-roberts** [comment]
4eabd97
