### ISSUE TITLE
Tutorial error for recursivePlot call

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#22]
%%Plot 4D data section broken on dev around line 213 when calling recursivePlot. note this occurs before I merge in my new branch.

**Comment by davestanley** [comment]
I tried replicating this, but couldn't reproduce the error. Maybe other changes have since fixed this. Can you verify @erik-roberts / @benpolletta  ?

**Comment by erik-roberts** [comment]
don't get error any more. must have been fixed elsewhere.
