### ISSUE TITLE
reset and constructor methods should yield same object

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#24]
right now I has a 2d axis, the other a 1d. also one has a meta.datainfo and other is empty meta.

**Comment by erik-roberts** [comment]
@davestanley @benpolletta does this seem like it should be fixed?

**Comment by erik-roberts** [comment]
you could just have reset call constructor if they should be the same. is there a reason to keep them different?

**Comment by davestanley** [comment]
Yes, this makes sense - new objects should always be 2D axes (I’m not even sure how you got a 1D one). I see no reason not to have reset call the constructor.

**Comment by erik-roberts** [comment]
Well, reset basically makes it a new array, as if you called the constructor. so calling the constructor from within reset would get that behavior.

from:
```matlab
function [obj] = reset(obj)

obj.data_pr = [];
obj.axis_pr = obj.axisClass;
obj.meta = struct;

end
```

to:
```matlab
function [obj] = reset(obj)

obj = nDDict;

end
```

as you can see, this makes a 1d axis, which gets converted later in most code that calls reset.  but calling reset alone won't make it 2d.
```matab
>> a=nDDict

a = 

  0×0 nDDict array with properties:

    meta: [1×1 struct]
    data: []
    axis: [1×2 nDDictAxis]

>> a.reset

ans = 

  nDDict with properties:

    meta: [1×1 struct]
    data: []
    axis: [1×1 nDDictAxis]
```

**Comment by erik-roberts** [comment]
```matab
>> a=nDDict

a = 

  0×0 nDDict array with properties:

    meta: [1×1 struct]
    data: []
    axis: [1×2 nDDictAxis]

>> a.reset

ans = 

  nDDict with properties:

    meta: [1×1 struct]
    data: []
    axis: [1×1 nDDictAxis]
```

**Comment by erik-roberts** [comment]
actually, it seems we should have it find the current object's constructor, and then call that, since it might be a subclass.

**Comment by erik-roberts** [comment]
11eb767
