### ISSUE TITLE
Rename to MDict and MDictAxis

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#27]

**Comment by davestanley** [comment]
Also, merge xPlt and nDDict into a single class (no more subclassing of xPlt)

The reason for this is because the xPlt functions can actually be used for **more** than just plotting (e.g. data analysis). So we can merge this into one class

**Comment by davestanley** [comment]
Doing this rename now...

**Comment by davestanley** [comment]
Finished doing the rename in branch iss27. Now I'm going to merge xPlt and nDDict into a single class

**Comment by davestanley** [comment]
I'm actually going to use MDict and MDictAxis instead of MDD or MDDict, since MDD by itself is already taken on GitHub and impossible to search. Also, MDDict is too hard to say.

**Comment by davestanley** [comment]
Finished the rename for both DynaSim and MDict

**Comment by davestanley** [comment]
Multiple people misheard the name _MDict_ as something inappropriate/offensive. Renaming back to MDD.

**Comment by erik-roberts** [comment]
can we close this?

**Comment by erik-roberts** [comment]
@davestanley ?
