### ISSUE TITLE
add regular expression trigger

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#30]
an issue with automatic use of regular expressions is that sometimes one desires regular expression syntax without triggering a regular expression.  I'm thinking ahead to if one imports a CSV directly and there's periods or other symbols in the names from some hash, weird hardware, or filenames.

In vim, one uses `'/pattern/'`, so I would suggest using slashes like that to trigger a re.

**Comment by erik-roberts** [comment]
@davestanley @benpolletta how do you feel about this?

**Comment by davestanley** [comment]
So to confirm:  you mean like a specific character like '/' to force MDD to use the regex_lookup ? If regular expressions aren't triggered, and the user specifies a string, what would be the behavior in this case? 
I'm not too familiar with regexp's ,but wouldn't you just use an escape sequence to handle this?

**Comment by davestanley** [comment]
I like this idea in theory. So in the case without regexp, would we just check if the supplied search string is a 1:1 match between the supplied possible values and the selection?

`[selection_out, startIndex] = regex_lookup(vals, selection)`

**Comment by erik-roberts** [comment]
I don't think there is a general regular expression escape sequence for raw string.  If there is a string, it should use `strfind` normally, so it can find substrings, but just not using regular expression syntax. But preferably, one would use the numerical index for the string position, or use valSubset if wanting to subset by value instead of index.

You typically use `/` at beginning and end to trigger a regexp.

**Comment by erik-roberts** [comment]
branch: iss30_re_trigger
also updated tutorial.

**Comment by erik-roberts** [comment]
fc471491395473e3afd411306811b4b79611955a
