### ISSUE TITLE
Tagging of functions

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#33]
I added tags to streamline the editing process, to mark things that need completion, etc. In particular, even if we can 't do complete documentation at this stage, it would be helpful to add examples to demos_xPlt as we go along and add functionality. 

Here are some of the tags I have added
```
% % Developer notes:
% I am adding the following hash tags to the code as a way of marking
% things that need to be done / investigated.
% #whowrotethis - Requested author information
% #makeprivate - Perhaps make the function private
% #isitoutdated - This might be outdated - if so, remove
% #Toimplement
% #requestexample - requests an example of implementation of this code in demos_xPlt


```

**Comment by erik-roberts** [comment]
moving to wiki
