### ISSUE TITLE
Rename importLinearData to importDataTable

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#36]
There are some issues with inconsistency between importData and importLinearData. First, importLinearData is really taking in a table. Second, importData can also accept axis names, whereas importLinearData cannot.

Originally, these two methods are defined as follows
`function obj = importData(obj,data,axis_vals,axis_names)`
`function obj = importLinearData(obj,X,varargin)`

I'm renaming the method `importLinearData` to `importDataTable`.

Also its new function definition will be as follows:
`obj = importDataTable(obj,data_column,axis_val_columns,axis_names)`

I'm going to update all references to importLinearData in both DynaSim and MDD accordingly.

**Comment by davestanley** [comment]
Still to do: Add example of importing linear data into xPlt tutorial file!

**Comment by erik-roberts** [comment]
Note: matlab has something called a table which may be confusing, so in the docs you should clarify.  I'll make an issue for adding support for importing a table also.
https://www.mathworks.com/help/matlab/ref/table.html

**Comment by davestanley** [comment]
@erik-roberts Do we expect many people will use the MATLAB Table class? Is there any advantage to using it? I feel like we have our bases covered with importData and importDataTable (for high dimensional data and 2D data tables, respectively), but it probably wouldn't be much additional work to allow the table class too

**Comment by davestanley** [comment]
The complication is that, with the 2D data table format, there there are different restrictions on the columns' data types . The first column can be anything; the 2nd to last columns must be numerics, cellnums, or cellstrings

**Comment by erik-roberts** [comment]
If people are advanced enough to use a table, they are likely advanced enough to convert it to a cell array for `importDataTable`, so that's fine to not add support.

**Comment by erik-roberts** [comment]
i think the tutorial example is still left to do.

**Comment by erik-roberts** [comment]
finished

**Comment by erik-roberts** [comment]
6459965
