### ISSUE TITLE
Make import methods static

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#39]
Make import methods static methods that can take an object. This allows for 2 different interfaces:
```matlab
obj = ndDict;
obj = obj.importMethod(data);

%or

obj = ndDict.ImportMethod(data);
```

**Comment by erik-roberts** [comment]
iss39_static_import_methods

**Comment by erik-roberts** [comment]
downside: had to hack subrefs if using just static functions, so switching to 2 different cases of function, upper and lower. upper will be static.

**Comment by davestanley** [comment]
Did you implement this already? 

This might work with importData, but it would not work with importAxisNames or importAxisVals, since these would depend on obj.data already being populated (e.g. since they call checkDims / fixAxis)

**Comment by erik-roberts** [comment]
The best option was to make separate methods with uppercase name due to some issues with subclass ease. I'm implementing in the branch I listed above. Yes, it's only for the data importing methods (3 so far).

**Comment by davestanley** [comment]
Ok, I was going to do the rename of nDDict to MDD shortly, but I'll hold off on this until you're done with this

**Comment by erik-roberts** [comment]
ae3095a6928fc0be1d0ebe3a9530a2a5496c8d85

**Comment by davestanley** [comment]
@erik-roberts What is the advantage of having these two options?

Wouldn't calling importData via the constructor encompass the "call as a static class method" option?

**Comment by erik-roberts** [comment]
The advantage is having full control and specificity. Also, there is an advantage with tab completion to see the different import option quickly.

Calling via the constructor is an alias for a static method call, but the interface may change, and also currently and in the future probably won't support all import functions. For example, importFile can't be used currently with the constructor.
