### ISSUE TITLE
recursivePlot should handle arbitrary dimensions.

### ISSUE THREAD

**Issue by benpolletta** [davestanley/MDD#4]
Debug recursivePlot_2.

**Comment by davestanley** [comment]
I'll commit these changes shortly. I'll also take a stab at writing documentation for recursivePlot.

**Comment by benpolletta** [comment]
Closed by f5403c2002c54739fae0ca07d64e144d43d99858. recursiveFunc_2 now works in the tutorial, and I've replaced recursiveFunc's body with the body of recursiveFunc_2.
