### ISSUE TITLE
Export to linear data

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#40]

**Comment by davestanley** [comment]
Writing this function now

**Comment by davestanley** [comment]
Still need to write method description for this command

**Comment by erik-roberts** [comment]
we should extend this to allow for export to txt/csv tables, which will require unpacking of dims. and then just make an exportToCSV method.

**Comment by erik-roberts** [comment]
added export to tutorial

**Comment by erik-roberts** [comment]
6459965
