### ISSUE TITLE
tutorial_MDict: Write example of data analysis using recursiveFunc

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#47]
So far, all the example uses of recursiveFunc involve plotting. Write an example instead that involves signal processing.

**Comment by davestanley** [comment]
@benpolletta Ben, would you have any ideas for this?

**Comment by benpolletta** [comment]
Sure, I can put one in. I'll put it on my to-do list.

**Comment by davestanley** [comment]
Thanks Ben!

**Comment by benpolletta** [comment]
99e89894fc13ead5b8bdeb2413a5f466a97b0ade
