### ISSUE TITLE
make data and axis non-dependent

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#57]
We don't need data and axis to be private in order to have a separate setter that runs checkDims. However, it may be useful to have private properties in order to bypass the checkDims. However, if we always run checkDims right after setting, then it might as well be non-dependent.
https://www.mathworks.com/help/matlab/matlab_oop/property-access-methods.html

**Comment by erik-roberts** [comment]
i think the bypassing is worth keeping the dependence.

**Comment by davestanley** [comment]
I agree, there might be some situations in which we would want to bypass checkDims internally. Best to keep dependence.

Have you encountered any situations in which you want to bypass checkdims externally?

**Comment by davestanley** [comment]
I agree, there might be some situations in which we would want to bypass checkDims internally. Best to keep dependence.

Have you encountered any situations in which you want to bypass checkdims externally? Perhaps we could create a way to bypass this if need be
