### ISSUE TITLE
linear merge doesn't handle axis names correctly

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#61]
If one object has axis names changed around from default, linear merge concatenates them without rearranging.

**Comment by benpolletta** [comment]
I wrote the alignAxes method to handle this. What's tricky is figuring out
how to apply it in merge - the ideal would be to have it align all the axis
names that are present in both objects to be merged. I'm not sure how merge
handles objects with different numbers of axes. I'll look into it, but
y'all's thoughts would be appreciated.

**Comment by erik-roberts** [comment]
TODO
* i wrote something like alignAxes in the new merge, but it allows  for non equal axes. that should be migrated to a new fn.
* also might be good to use intersect in align axes to vectorize the for loop.

**Comment by erik-roberts** [comment]
linear merge can't handle different number of axes.  it would be really hard to fix that without replicating most of normal merge, which solved this problem and is faster. i think linearMerge is now deprecated, and maybe should be removed since merge is superior in every way i think. we should debug it for now and use linear merge if/when there's a bug in merge.

**Comment by davestanley** [comment]
I suggest, for debugging purposes, we write a short method that 
1. Runs both merge and linear merge
2. Tracks the time of both
3. Throws an error when there is a discrepancy and a warning when linear merge is faster (a cheap way of identifying if there are any situations in which linear merge is actually more efficient)
