### ISSUE TITLE
allow linear indexing from subset

### ISSUE THREAD

**Issue by erik-roberts** [davestanley/MDD#64]
https://www.mathworks.com/help/matlab/math/matrix-indexing.html#f1-85511

**Comment by davestanley** [comment]
Working on this

**Comment by davestanley** [comment]
This should be working now.

**Comment by davestanley** [comment]
Note that this allows hybrid indexing, such as xp('v','E',1:9), where 1:9 is considered a linear index (see tutorial_MDD.m)

Also, note: `end` still doesn't work. See issue #76
