### ISSUE TITLE
MDDRef bug in constructor when setting valueObjClass

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#73]
I encountered a bug when using the following format of the constructor
`obj = MDDRef(valueObjClass, data, axis_vals, axis_names) % for subclassing MDD`

```
>> xp7 = MDDRef(myMDDSubclass);
Index exceeds matrix dimensions.
Error in MDDRef (line 47)
            if nargin && (isobject(varargin{1}) && isa(varargin{1}, 'MDD')) 
```

@erik-roberts , can you take a look? The fix is probably simple, but I don't want to mess with your code

**Comment by davestanley** [comment]
Or is this simply a use case that is not permitted?

**Comment by erik-roberts** [comment]
3166b62
