### ISSUE TITLE
Write debugging method for merge vs linearmerge

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#74]
I suggest, for debugging purposes, we write a short method that 
1. Runs both merge and linear merge
2. Tracks the time of both
3. Throws an error when there is a discrepancy and a warning when linear merge is faster (a cheap way of identifying if there are any situations in which linear merge is actually more efficient)

See #61 . We can run this quickly through the tutorials_MDD script

**Comment by erik-roberts** [comment]
to clarify, is this a one time thing, or an ongoing testing?

**Comment by davestanley** [comment]
I was thinking of it as ongoing testing. Let me implement it first and then tell me what you think :)

**Comment by davestanley** [comment]
Done. Set debugBool to `true` in order to compare speeds
