### ISSUE TITLE
Automatically enter valSubset mode if a query string is supplied

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#87]
Given:

```
xp.printAxisInfo
Axis Size: [3  3  2  8]
Axis 1: E_Iapp (numeric) -> 0, 10, 20
Axis 2: I_E_tauD (numeric) -> 5, 10, 15
Axis 3: populations (cellstr) -> E, I
Axis 4: variables (cellstr) -> v, iNa_m, iNa_h, iK_n, I_iGABAa_s, E_iAMPA_s, I_iGABAa_ISYN, E_iAMPA_ISYN
```

I want to be able to run, `xp('x>5',:,:,:)`. Currently, running this returns an error. I want it to behave in the same way as `xp.valSubset('x>5',:,:,:)`, which works properly. 

We should modify indexing (subscript method) so that, when a string is used to index a numeric axis, it automatically uses the valSubset method of indexing.

Ideally, in the future, I would like to merge the valSubset method seamlessly into default indexing.

@erik-roberts , how does this sound?

**Comment by erik-roberts** [comment]
probably fine. i can't immediately think of a situation in which that would cause issues. in general, indexing isn't always consistent, so it would be nice to have it be more so.
