### ISSUE TITLE
abs() and other methods that assume obj.data_pr is numeric

### ISSUE THREAD

**Issue by davestanley** [davestanley/MDD#9]
Since obj.data_pr can be a cell array, I would rather not include functions like abs() in the core nDDims code that make assumptions of what this cell array contains. 

Rather, I would prefer to err on the side of keeping the *core* nDDims methods as simple as possible and not including methods like abs(). The reason for this is :
(A) The user can easily write them themselves
(B) They will produce errors when data_pr contains, for example, strings.
(C) Simpler, and sticking to core MATALB conventions, is better. For example, running abs(X) where X is a cell array will return an error.

I realize that we do already have some functions, like pack/unpackDims , which assumes data_pr is a cell array of matrices. I think we can justify making an exception here since pack/unpackDims is incredibly useful and also would be complicated job for an end user to write on his/her own. (We just need to make sure to include appropraite error checking to make sure data_pr contains matrices)

**Comment by davestanley** [comment]
To do: Remove obj.abs() method from nDDict and add it as a standalone function (e.g. absc(), which would be abs() extended to operate on cell arrays via a cell fun call; this would work on all cell arrays, not just nDDict objects).

@benpolletta , can you do this?

**Comment by benpolletta** [comment]
Sure thing.
